# Generated by Django 3.0.5 on 2020-04-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='image',
            field=models.ImageField(default='pharmacy/static/img/no_image.webp', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(default='pharmacy/static/img/no_image.webp', upload_to='img/'),
        ),
    ]
