# Generated by Django 3.0.5 on 2020-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20200410_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
