# Generated by Django 3.0.5 on 2020-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20200410_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='image',
            field=models.ImageField(default='images/no_image.webp', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(default='images/no_image.webp', upload_to='images/'),
        ),
    ]
