# Generated by Django 3.0.5 on 2020-04-10 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20200410_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='description_drugs', to='pharmacy.Description'),
        ),
    ]
