# Generated by Django 3.0.5 on 2020-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_description_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugpharmacy',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
